const BANK = [

/* ================= NHÓM 1 ================= */

{id:1,group:1,q:`Nghiệm của phương trình $\log_{3}(5x)=2$ là`,A:`$x=\\dfrac{8}{5}$`,B:`$x=9$`,C:`$x=\\dfrac{9}{5}$`,D:`$x=8$`,correct:"C"},
{id:2,group:1,q:`Nghiệm của phương trình $\log_{2}(5x)=3$ là`,A:`$x=\\dfrac{8}{5}$`,B:`$x=\\dfrac{9}{5}$`,C:`$x=8$`,D:`$x=9$`,correct:"A"},
{id:3,group:1,q:`Nghiệm của phương trình $\log_{2}(3x)=3$ là`,A:`$x=3$`,B:`$x=2$`,C:`$x=\\dfrac{8}{3}$`,D:`$x=\\dfrac{1}{2}$`,correct:"C"},
{id:4,group:1,q:`Nghiệm của phương trình $\log_{5}(3x)=2$ là`,A:`$x=25$`,B:`$x=\\dfrac{32}{3}$`,C:`$x=32$`,D:`$x=\\dfrac{25}{3}$`,correct:"D"},
{id:5,group:1,q:`Nghiệm của phương trình $\log_{3}(2x)=2$ là`,A:`$x=\\dfrac{9}{2}$`,B:`$x=9$`,C:`$x=4$`,D:`$x=8$`,correct:"A"},
{id:6,group:1,q:`Nghiệm của phương trình $\log_{3}(2x-1)=2$ là`,A:`$x=3$`,B:`$x=5$`,C:`$x=\\dfrac{9}{2}$`,D:`$x=\\dfrac{7}{2}$`,correct:"B"},
{id:7,group:1,q:`Nghiệm của phương trình $\log_{3}(x-1)=2$ là`,A:`$x=8$`,B:`$x=9$`,C:`$x=7$`,D:`$x=10$`,correct:"D"},
{id:8,group:1,q:`Nghiệm của phương trình $\log_{2}(x-2)=3$ là`,A:`$x=6$`,B:`$x=8$`,C:`$x=11$`,D:`$x=10$`,correct:"D"},
{id:9,group:1,q:`Nghiệm của phương trình $\log_{3}(x-2)=2$ là`,A:`$x=11$`,B:`$x=10$`,C:`$x=7$`,D:`$x=8$`,correct:"A"},
{id:10,group:1,q:`Nghiệm của phương trình $\log_{2}(x+9)=5$ là`,A:`$x=41$`,B:`$x=23$`,C:`$x=1$`,D:`$x=16$`,correct:"B"},
{id:11,group:1,q:`Nghiệm của phương trình $\log_{2}(x+6)=5$ là`,A:`$x=4$`,B:`$x=19$`,C:`$x=38$`,D:`$x=26$`,correct:"D"},
{id:12,group:1,q:`Nghiệm của phương trình $\log_{2}(x+7)=5$ là`,A:`$x=18$`,B:`$x=25$`,C:`$x=39$`,D:`$x=3$`,correct:"B"},
{id:13,group:1,q:`Nghiệm của phương trình $\log_{2}(x+8)=5$ là`,A:`$x=17$`,B:`$x=24$`,C:`$x=2$`,D:`$x=40$`,correct:"B"},
{id:14,group:1,q:`Tập nghiệm của phương trình $\log_{2}(x^2-x+2)=1$ là`,A:`$\{0\}$`,B:`$\{0;1\}$`,C:`$\{-1;0\}$`,D:`$\{1\}$`,correct:"B"},
{id:15,group:1,q:`Giải phương trình $\log_{4}(x-1)=3$`,A:`$x=65$`,B:`$x=80$`,C:`$x=82$`,D:`$x=63$`,correct:"A"},
{id:16,group:1,q:`Tìm nghiệm của phương trình $\log_{2}(1-x)=2$`,A:`$x=5$`,B:`$x=-3$`,C:`$x=-4$`,D:`$x=3$`,correct:"B"},
{id:17,group:1,q:`Tập nghiệm của phương trình $\log_{2}(x^2-1)=3$ là`,A:`$\{-\sqrt{10};\sqrt{10}\}$`,B:`$\{-3;3\}$`,C:`$\{-3\}$`,D:`$\{3\}$`,correct:"B"},
{id:18,group:1,q:`Tìm nghiệm của phương trình $\log_{2}(x-5)=4$`,A:`$x=11$`,B:`$x=13$`,C:`$x=21$`,D:`$x=3$`,correct:"C"},
{id:19,group:1,q:`Tập nghiệm của phương trình $\log_{3}(x^2-7)=2$ là`,A:`$\{4\}$`,B:`$\{-4\}$`,C:`$\{-\sqrt{15};\sqrt{15}\}$`,D:`$\{-4;4\}$`,correct:"D"},
{id:20,group:1,q:`Tìm nghiệm của phương trình $\log_{25}(x+1)=\\dfrac{1}{2}$`,A:`$x=6$`,B:`$x=4$`,C:`$x=\\dfrac{23}{2}$`,D:`$x=-6$`,correct:"B"},
{id:21,group:1,q:`Phương trình $\log_{3}(3x-2)=3$ có nghiệm là`,A:`$x=\\dfrac{25}{3}$`,B:`$x=87$`,C:`$x=\\dfrac{29}{3}$`,D:`$x=\\dfrac{11}{3}$`,correct:"C"},
{id:22,group:1,q:`Tập nghiệm của phương trình $\log_{3}(x^2+x+3)=1$ là`,A:`$\{-1;0\}$`,B:`$\{0;1\}$`,C:`$\{0\}$`,D:`$\{-1\}$`,correct:"A"},
{id:23,group:1,q:`Tập nghiệm của phương trình $\log(x^2-2x+2)=1$ là`,A:`$\varnothing$`,B:`$\{-2;4\}$`,C:`$\{4\}$`,D:`$\{-2\}$`,correct:"B"},
{id:24,group:1,q:`Tập nghiệm của phương trình $\log_{3}(x^2+2x)=1$ là`,A:`$\{1;-3\}$`,B:`$\{1;3\}$`,C:`$\{0\}$`,D:`$\{-3\}$`,correct:"A"},
{id:25,group:1,q:`Nghiệm của phương trình $\log_{2}(x+4)=3$ là`,A:`$x=5$`,B:`$x=4$`,C:`$x=2$`,D:`$x=12$`,correct:"B"},
{id:26,group:1,q:`Nghiệm của phương trình $\log_{1/2}(2x-1)=0$ là`,A:`$x=\\dfrac{3}{4}$`,B:`$x=1$`,C:`$x=\\dfrac{1}{2}$`,D:`$x=\\dfrac{2}{3}$`,correct:"B"},
  /* ================= NHÓM 2 ================= */

{id:27,group:2,q:`Giải phương trình $2^x=8$`,A:`$x=2$`,B:`$x=3$`,C:`$x=4$`,D:`$x=1$`,correct:"B"},
{id:28,group:2,q:`Giải phương trình $3^x=9$`,A:`$x=2$`,B:`$x=3$`,C:`$x=1$`,D:`$x=4$`,correct:"A"},
{id:29,group:2,q:`Giải phương trình $5^x=25$`,A:`$x=2$`,B:`$x=3$`,C:`$x=1$`,D:`$x=4$`,correct:"A"},
{id:30,group:2,q:`Giải phương trình $4^x=16$`,A:`$x=3$`,B:`$x=4$`,C:`$x=2$`,D:`$x=1$`,correct:"C"},
{id:31,group:2,q:`Giải phương trình $9^x=3$`,A:`$x=\\dfrac12$`,B:`$x=2$`,C:`$x=3$`,D:`$x=1$`,correct:"A"},
{id:32,group:2,q:`Giải phương trình $27^x=3$`,A:`$x=\\dfrac12$`,B:`$x=\\dfrac13$`,C:`$x=1$`,D:`$x=3$`,correct:"B"},
{id:33,group:2,q:`Giải phương trình $2^{x+1}=8$`,A:`$x=2$`,B:`$x=1$`,C:`$x=3$`,D:`$x=4$`,correct:"A"},
{id:34,group:2,q:`Giải phương trình $3^{x-1}=9$`,A:`$x=2$`,B:`$x=3$`,C:`$x=1$`,D:`$x=4$`,correct:"B"},
{id:35,group:2,q:`Giải phương trình $5^{2x}=25$`,A:`$x=1$`,B:`$x=2$`,C:`$x=\\dfrac12$`,D:`$x=3$`,correct:"A"},
{id:36,group:2,q:`Giải phương trình $4^{2x}=16$`,A:`$x=1$`,B:`$x=2$`,C:`$x=\\dfrac12$`,D:`$x=3$`,correct:"A"},
{id:37,group:2,q:`Giải phương trình $2^{x}=\\dfrac{1}{4}$`,A:`$x=2$`,B:`$x=-2$`,C:`$x=-1$`,D:`$x=\\dfrac12$`,correct:"B"},
{id:38,group:2,q:`Giải phương trình $3^{x}=\\dfrac{1}{9}$`,A:`$x=-2$`,B:`$x=2$`,C:`$x=-1$`,D:`$x=\\dfrac12$`,correct:"A"},
{id:39,group:2,q:`Giải phương trình $5^{x}=\\dfrac{1}{25}$`,A:`$x=2$`,B:`$x=-2$`,C:`$x=-1$`,D:`$x=\\dfrac12$`,correct:"B"},
{id:40,group:2,q:`Giải phương trình $2^{x+2}=32$`,A:`$x=3$`,B:`$x=2$`,C:`$x=1$`,D:`$x=4$`,correct:"A"},
{id:41,group:2,q:`Giải phương trình $3^{x+1}=27$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"B"},
{id:42,group:2,q:`Giải phương trình $5^{x-1}=5$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"B"},
{id:43,group:2,q:`Giải phương trình $2^{2x}=8$`,A:`$x=\\dfrac32$`,B:`$x=2$`,C:`$x=1$`,D:`$x=\\dfrac12$`,correct:"A"},
{id:44,group:2,q:`Giải phương trình $3^{2x}=9$`,A:`$x=1$`,B:`$x=2$`,C:`$x=\\dfrac12$`,D:`$x=3$`,correct:"A"},
{id:45,group:2,q:`Giải phương trình $4^{x-2}=4$`,A:`$x=3$`,B:`$x=4$`,C:`$x=2$`,D:`$x=1$`,correct:"A"},
{id:46,group:2,q:`Giải phương trình $5^{x+1}=125$`,A:`$x=2$`,B:`$x=3$`,C:`$x=1$`,D:`$x=4$`,correct:"A"},
{id:47,group:2,q:`Giải phương trình $2^{x-3}=1$`,A:`$x=3$`,B:`$x=2$`,C:`$x=1$`,D:`$x=0$`,correct:"A"},
{id:48,group:2,q:`Giải phương trình $3^{x}=1$`,A:`$x=0$`,B:`$x=1$`,C:`$x=-1$`,D:`$x=2$`,correct:"A"},
{id:49,group:2,q:`Giải phương trình $10^{x}=1$`,A:`$x=1$`,B:`$x=0$`,C:`$x=-1$`,D:`$x=2$`,correct:"B"},
  /* ================= NHÓM 3 ================= */

{id:50,group:3,q:`Giải phương trình $2^x+2^{x+1}=12$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"B"},
{id:51,group:3,q:`Giải phương trình $3^x+3^{x+1}=36$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"B"},
{id:52,group:3,q:`Giải phương trình $5^x+5^{x+1}=150$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"A"},
{id:53,group:3,q:`Giải phương trình $2^{2x}-8=0$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=\\dfrac32$`,correct:"D"},
{id:54,group:3,q:`Giải phương trình $3^{2x}-9=0$`,A:`$x=1$`,B:`$x=2$`,C:`$x=\\dfrac12$`,D:`$x=3$`,correct:"A"},
{id:55,group:3,q:`Giải phương trình $4^x-2^x-2=0$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"B"},
{id:56,group:3,q:`Giải phương trình $9^x-3^x-6=0$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"A"},
{id:57,group:3,q:`Giải phương trình $2^{x+1}+2^x=24$`,A:`$x=2$`,B:`$x=3$`,C:`$x=4$`,D:`$x=5$`,correct:"B"},
{id:58,group:3,q:`Giải phương trình $3^{x+1}+3^x=108$`,A:`$x=2$`,B:`$x=3$`,C:`$x=4$`,D:`$x=1$`,correct:"B"},
{id:59,group:3,q:`Giải phương trình $5^{x+1}+5^x=750$`,A:`$x=2$`,B:`$x=1$`,C:`$x=3$`,D:`$x=4$`,correct:"A"},
{id:60,group:3,q:`Giải phương trình $2^{2x}+2^x-6=0$`,A:`$x=1$`,B:`$x=2$`,C:`$x=\\dfrac12$`,D:`$x=3$`,correct:"A"},
{id:61,group:3,q:`Giải phương trình $3^{2x}+3^x-12=0$`,A:`$x=1$`,B:`$x=2$`,C:`$x=\\dfrac12$`,D:`$x=3$`,correct:"A"},
{id:62,group:3,q:`Giải phương trình $4^x-4=0$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=0$`,correct:"A"},
{id:63,group:3,q:`Giải phương trình $8^x-2=0$`,A:`$x=\\dfrac13$`,B:`$x=1$`,C:`$x=2$`,D:`$x=3$`,correct:"A"},
{id:64,group:3,q:`Giải phương trình $9^x-27=0$`,A:`$x=\\dfrac32$`,B:`$x=1$`,C:`$x=2$`,D:`$x=3$`,correct:"A"},
{id:65,group:3,q:`Giải phương trình $2^{x}-3\\cdot2^{x-1}=0$`,A:`$x=1$`,B:`$x=0$`,C:`$x=2$`,D:`$x=3$`,correct:"A"},
{id:66,group:3,q:`Giải phương trình $3^{x}-4\\cdot3^{x-1}=0$`,A:`$x=1$`,B:`$x=0$`,C:`$x=2$`,D:`$x=3$`,correct:"A"},
{id:67,group:3,q:`Giải phương trình $5^{x}-6\\cdot5^{x-1}=0$`,A:`$x=1$`,B:`$x=0$`,C:`$x=2$`,D:`$x=3$`,correct:"A"},
{id:68,group:3,q:`Giải phương trình $2^{x+2}-4\\cdot2^x=0$`,A:`$x=1$`,B:`$x=0$`,C:`$x=2$`,D:`$x=3$`,correct:"A"},
{id:69,group:3,q:`Giải phương trình $3^{x+2}-9\\cdot3^x=0$`,A:`$x=1$`,B:`$x=0$`,C:`$x=2$`,D:`$x=3$`,correct:"A"},
{id:70,group:3,q:`Giải phương trình $4^{x+1}-4\\cdot4^x=0$`,A:`$x=1$`,B:`$x=0$`,C:`$x=2$`,D:`$x=3$`,correct:"A"},
{id:71,group:3,q:`Giải phương trình $2^{x}+4^{x}=20$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"B"},
{id:72,group:3,q:`Giải phương trình $3^{x}+9^{x}=30$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"A"},
{id:73,group:3,q:`Giải phương trình $5^{x}+25^{x}=150$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"A"},
{id:74,group:3,q:`Giải phương trình $2^{x+1}+4^{x}=40$`,A:`$x=2$`,B:`$x=3$`,C:`$x=1$`,D:`$x=4$`,correct:"A"},
{id:75,group:3,q:`Giải phương trình $3^{x+1}+9^{x}=90$`,A:`$x=1$`,B:`$x=2$`,C:`$x=3$`,D:`$x=4$`,correct:"A"},
{id:76,group:3,q:`Giải phương trình $2^{x}+2^{-x}=5$`,A:`$x=1$`,B:`$x=2$`,C:`$x=\\pm1$`,D:`$x=\\pm2$`,correct:"C"},
{id:77,group:3,q:`Giải phương trình $3^{x}+3^{-x}=10$`,A:`$x=1$`,B:`$x=2$`,C:`$x=\\pm1$`,D:`$x=\\pm2$`,correct:"A"},
  /* ================= NHÓM 4 ================= */

{id:78,group:4,q:`Giải phương trình $\\log_2(x-1)+\\log_2(x-3)=3$`,A:`$x=5$`,B:`$x=4$`,C:`$x=6$`,D:`$x=3$`,correct:"C"},
{id:79,group:4,q:`Giải phương trình $\\log_3(x-2)+\\log_3(x-4)=2$`,A:`$x=6$`,B:`$x=5$`,C:`$x=7$`,D:`$x=8$`,correct:"A"},
{id:80,group:4,q:`Giải phương trình $\\log(x)+\\log(x-1)=1$`,A:`$x=5$`,B:`$x=4$`,C:`$x=3$`,D:`$x=2$`,correct:"B"},
{id:81,group:4,q:`Giải phương trình $\\log_2(x^2-5x+6)=1$`,A:`$x=2$`,B:`$x=3$`,C:`$x=4$`,D:`$x=2;3$`,correct:"D"},
{id:82,group:4,q:`Giải phương trình $\\log_3(x^2-4)=2$`,A:`$x=\\pm4$`,B:`$x=\\pm3$`,C:`$x=4$`,D:`$x=3$`,correct:"B"},
{id:83,group:4,q:`Giải phương trình $\\log_2(x+1)=\\log_2(3x-5)$`,A:`$x=3$`,B:`$x=2$`,C:`$x=4$`,D:`$x=5$`,correct:"A"},
{id:84,group:4,q:`Giải phương trình $\\log_3(x+2)=\\log_3(2x-1)$`,A:`$x=3$`,B:`$x=2$`,C:`$x=1$`,D:`$x=4$`,correct:"A"},
{id:85,group:4,q:`Giải phương trình $\\log(x+3)=\\log(2x-1)$`,A:`$x=4$`,B:`$x=2$`,C:`$x=3$`,D:`$x=5$`,correct:"B"},
{id:86,group:4,q:`Giải phương trình $\\log_2(x)+\\log_2(x-2)=2$`,A:`$x=4$`,B:`$x=3$`,C:`$x=5$`,D:`$x=6$`,correct:"A"},
{id:87,group:4,q:`Giải phương trình $\\log_3(x)+\\log_3(x-3)=2$`,A:`$x=6$`,B:`$x=5$`,C:`$x=7$`,D:`$x=8$`,correct:"A"},
{id:88,group:4,q:`Giải phương trình $\\log(x)+\\log(x-9)=2$`,A:`$x=10$`,B:`$x=9$`,C:`$x=11$`,D:`$x=12$`,correct:"C"},
{id:89,group:4,q:`Giải phương trình $\\log_2(x^2-3x)=1$`,A:`$x=1;2$`,B:`$x=2;3$`,C:`$x=3;4$`,D:`$x=4;5$`,correct:"B"},
{id:90,group:4,q:`Giải phương trình $\\log_3(x^2-5x)=1$`,A:`$x=2;3$`,B:`$x=3;4$`,C:`$x=4;5$`,D:`$x=5;6$`,correct:"A"},
{id:91,group:4,q:`Giải phương trình $\\log_2(x-1)+\\log_2(x-2)=1$`,A:`$x=3$`,B:`$x=4$`,C:`$x=5$`,D:`$x=6$`,correct:"B"},
{id:92,group:4,q:`Giải phương trình $\\log_3(x-1)+\\log_3(x-2)=1$`,A:`$x=3$`,B:`$x=4$`,C:`$x=5$`,D:`$x=6$`,correct:"A"},
{id:93,group:4,q:`Giải phương trình $\\log(x)+\\log(x-4)=1$`,A:`$x=5$`,B:`$x=6$`,C:`$x=7$`,D:`$x=8$`,correct:"A"},
{id:94,group:4,q:`Giải phương trình $\\log_2(x^2-7x+10)=1$`,A:`$x=2;5$`,B:`$x=3;4$`,C:`$x=1;6$`,D:`$x=4;5$`,correct:"B"}
];
